apiVersion: v1
kind: Service
metadata:
  name: patient-service
  namespace: microservices
  labels:
    app: patient-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: patient-service
  ports:
    - name: http
      port: 80
      targetPort: http
